CREATE TABLE public.feminicidio (
    DEPARTAMENTO_CIRCUNSCRICAO TEXT NULL,
    SECCIONAL_CIRCUNSCRICAO TEXT NULL,
    MUNICIPIO_CIRCUNSCRICAO TEXT NULL,
    DP_CIRCUNSCRICAO TEXT NULL,
    HD TEXT NULL,
    NVITIMAS TEXT NULL,
    ID_DELEGACIA TEXT NULL,
    MES_ESTATISTICA TEXT NULL,
    ANO_ESTATISTICA TEXT NULL,
    DATAHORA_REGISTRO_BO TEXT NULL,
    NUM_BO TEXT NULL,
    ANO_BO TEXT NULL,
    MUNICIPIO_ELABORACAO TEXT NULL,
    DP_ELABORACAO TEXT NULL,
    SEC_ELABORACAO TEXT NULL,
    DEP_ELABORACAO TEXT NULL,
    DATA_FATO TEXT NULL,
    HORA_FATO TEXT NULL,
    DESC_TIPOLOCAL TEXT NULL,
    LOGRADOURO TEXT NULL,
    NUMERO_LOGRADOURO TEXT NULL,
    LATITUDE TEXT NULL,
    LONGITUDE TEXT NULL,
    TIPO_PESSOA TEXT NULL,
    SEXO_PESSOA TEXT NULL,
    IDADE_PESSOA TEXT NULL,
    DATA_NASCIMENTO_PESSOA TEXT NULL,
    COR_PELE TEXT NULL,
    PROFISSAO TEXT NULL,
    NATUREZA_APURADA TEXT NULL,
    DESDOBRAMENTO TEXT NULL
) tablespace pg_default;


COPY public.feminicidio FROM '/feminicidio.csv' DELIMITER ',' CSV HEADER 

